-- Create database
CREATE DATABASE IF NOT EXISTS GROCERY;

-- Create Table
CREATE TABLE IF NOT EXISTS GROCERY.GROCERY (
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY(NAME)
);